// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xuhzwywuhgtbdawfperb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh1aHp3eXd1aGd0YmRhd2ZwZXJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MjY4NDUsImV4cCI6MjA2NzMwMjg0NX0.DkSVhxCG8mL9EXYNHqc4j3o37zQdRrgy-mAVH6OtXPg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});